#!/usr/bin/env python3
"""Setup script to create all project files"""
import os
import json
from pathlib import Path

def create_file(filepath, content):
          path = Path(filepath)
          path.parent.mkdir(parents=True, exist_ok=True)
          with open(path, 'w') as f:
                        f.write(content)
                    print(f"✓ Created {filepath}")

# Backend Flask app
app_py = '''from flask import Flask, request, jsonify
from flask_cors import CORS
import sqlite3, json, os
from datetime import datetime

app = Flask(__name__)
CORS(app)
DB_PATH = os.getenv("DATABASE_URL", "nonprofits.db")

def get_db():
    conn = sqlite3.connect(DB_PATH)
        conn.row_factory = sqlite3.Row
            return conn

            @app.route("/api/search", methods=["GET"])
            def search():
                query = request.args.get("q", "")
                    sector = request.args.get("sector", "")
                        conn = get_db()
                            cursor = conn.cursor()
                                sql = "SELECT * FROM organizations WHERE 1=1"
                                    params = []
                                        if query:
                                                sql += " AND (name LIKE ? OR ein LIKE ?)"
                                                        params.extend([f"%{query}%", f"%{query}%"])
                                                            if sector == "church":
                                                                    sql += " AND ntee_code LIKE \'X%\'"
                                                                        elif sector == "disability":
                                                                                sql += " AND ntee_code LIKE \'J%\'"
                                                                                    elif sector == "children_families":
                                                                                            sql += " AND ntee_code LIKE \'B%\'"
                                                                                                sql += " ORDER BY alignment_score DESC LIMIT 100"
                                                                                                    cursor.execute(sql, params)
                                                                                                        results = [dict(row) for row in cursor.fetchall()]
                                                                                                            conn.close()
                                                                                                                return jsonify({"count": len(results), "results": results})
                                                                                                                
                                                                                                                @app.route("/api/stats", methods=["GET"])
                                                                                                                def stats():
                                                                                                                    conn = get_db()
                                                                                                                        cursor = conn.cursor()
                                                                                                                            cursor.execute("SELECT COUNT(*) as count FROM organizations")
                                                                                                                                total = dict(cursor.fetchone())["count"]
                                                                                                                                    conn.close()
                                                                                                                                        return jsonify({"total_organizations": total})
                                                                                                                                        
                                                                                                                                        @app.route("/api/health", methods=["GET"])
                                                                                                                                        def health():
                                                                                                                                            return jsonify({"status": "ok"})
                                                                                                                                            
                                                                                                                                            if __name__ == "__main__":
                                                                                                                                                app.run(debug=True, port=5000)
                                                                                                                                                \'\'\'
                                                                                                                                                
                                                                                                                                                init_db_py = '''import sqlite3, os
                                                                                                                                                DB_PATH = os.getenv("DATABASE_URL", "nonprofits.db")
                                                                                                                                                
                                                                                                                                                def init_database():
                                                                                                                                                    conn = sqlite3.connect(DB_PATH)
                                                                                                                                                        cursor = conn.cursor()
                                                                                                                                                            print("Creating tables...")
                                                                                                                                                                cursor.execute("""CREATE TABLE IF NOT EXISTS organizations (
                                                                                                                                                                        id INTEGER PRIMARY KEY, ein TEXT UNIQUE, name TEXT, state TEXT, city TEXT,
                                                                                                                                                                                mission TEXT, website TEXT, ntee_code TEXT, total_revenue DECIMAL,
                                                                                                                                                                                        alignment_score INTEGER DEFAULT 0, capacity_rating INTEGER DEFAULT 0)""")
                                                                                                                                                                                            cursor.execute("""CREATE TABLE IF NOT EXISTS prospect_lists (
                                                                                                                                                                                                    id INTEGER PRIMARY KEY, name TEXT, created_date TIMESTAMP)""")
                                                                                                                                                                                                        conn.commit()
                                                                                                                                                                                                            conn.close()
                                                                                                                                                                                                                print("✓ Database initialized")
                                                                                                                                                                                                                
                                                                                                                                                                                                                if __name__ == "__main__":
                                                                                                                                                                                                                    init_database()
                                                                                                                                                                                                                    \'\'\'
                                                                                                                                                                                                                    
                                                                                                                                                                                                                    download_py = '''import requests, zipfile, shutil
                                                                                                                                                                                                                    from pathlib import Path
                                                                                                                                                                                                                    
                                                                                                                                                                                                                    def download_990():
                                                                                                                                                                                                                        print("Downloading IRS 990 data (2024)...")
                                                                                                                                                                                                                            base = "https://apps.irs.gov/pub/epostcard/990/xml/2024"
                                                                                                                                                                                                                                data_dir = Path("990_data")
                                                                                                                                                                                                                                    data_dir.mkdir(exist_ok=True)
                                                                                                                                                                                                                                        extract_dir = Path("990_extracts")
                                                                                                                                                                                                                                            if extract_dir.exists():
                                                                                                                                                                                                                                                    shutil.rmtree(extract_dir)
                                                                                                                                                                                                                                                        extract_dir.mkdir(exist_ok=True)
                                                                                                                                                                                                                                                            months = ["01A", "02A", "03A", "04A", "05A"]
                                                                                                                                                                                                                                                                for month in months:
                                                                                                                                                                                                                                                                        url = f"{base}/2024_TEOS_XML_{month}.zip"
                                                                                                                                                                                                                                                                                filepath = data_dir / f"{month}.zip"
                                                                                                                                                                                                                                                                                        try:
                                                                                                                                                                                                                                                                                                    print(f"  {month}...", end=" ")
                                                                                                                                                                                                                                                                                                                r = requests.get(url, timeout=30)
                                                                                                                                                                                                                                                                                                                            if r.status_code == 200:
                                                                                                                                                                                                                                                                                                                                            with open(filepath, "wb") as f:
                                                                                                                                                                                                                                                                                                                                                                f.write(r.content)
                                                                                                                                                                                                                                                                                                                                                                                with zipfile.ZipFile(filepath, "r") as z:
                                                                                                                                                                                                                                                                                                                                                                                                    z.extractall(extract_dir)
                                                                                                                                                                                                                                                                                                                                                                                                                    print("✓")
                                                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                print("✗")
                                                                                                                                                                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"✗ ({e})")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("✓ Download complete")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            download_990()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            \'\'\'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            package_json = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "name": "prospect-harvester",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "version": "1.0.0",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "dependencies": {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "react": "^18.2.0",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "react-dom": "^18.2.0"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "scripts": {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "start": "react-scripts start",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "build": "react-scripts build"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "devDependencies": {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "react-scripts": "5.0.1"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    app_jsx = '''import React, { useState } from "react";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    import "./App.css";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default function App() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const [query, setQuery] = useState("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const [sector, setSector] = useState("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const [results, setResults] = useState([]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const search = async (e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            e.preventDefault();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const res = await fetch(`http://localhost:5000/api/search?q=${query}&sector=${sector}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const data = await res.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setResults(data.results || []);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="app">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h1>🎯 Prospect Harvester</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <form onSubmit={search}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input placeholder="Search..." value={query} onChange={(e) => setQuery(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <select value={sector} onChange={(e) => setSector(e.target.value)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <option value="">All</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="church">Churches</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option value="disability">Disability</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <option value="children_families">Children</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button>Search</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="results">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {results.map((org) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div key={org.id} className="card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3>{org.name}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>{org.city}, {org.state}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>Alignment: {org.alignment_score}/5</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            \'\'\'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            app_css = '''* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: sans-serif; background: #f5f5f5; }
.app { max-width: 1200px; margin: 0 auto; padding: 40px 20px; }
h1 { margin-bottom: 30px; color: #2563eb; }
form { display: flex; gap: 10px; margin-bottom: 30px; }
input, select { flex: 1; padding: 10px; border: 1px solid #ddd; border-radius: 4px; }
button { padding: 10px 20px; background: #2563eb; color: white; border: none; border-radius: 4px; cursor: pointer; }
.results { display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 20px; }
.card { background: white; padding: 20px; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
\'\'\'

index_js = '''import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";

ReactDOM.createRoot(document.getElementById("root")).render(<App />);
\'\'\'

index_html = '''<!DOCTYPE html>
<html lang="en">
<head>
              <meta charset="UTF-8" />
                               <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                                   <title>Prospect Harvester</title>
                                   </head>
                                   <body>
                                       <div id="root"></div>
                                       </body>
                                       </html>
                                       \'\'\'

                                       requirements = "Flask==2.3.0\nFlask-CORS==4.0.0\nrequests==2.31.0\nlxml==4.9.2\nxmltodict==0.13.0\npython-dotenv==1.0.0\n"

                                       env_file = "FLASK_ENV=development\nDATABASE_URL=nonprofits.db\n"

                                       print("=" * 50)
                                       print("PROSPECT HARVESTER - SETUP")
                                       print("=" * 50)

                                       create_file("backend/app.py", app_py)
                                       create_file("backend/init_db.py", init_db_py)
                                       create_file("backend/scripts/download_990.py", download_py)
                                       create_file("backend/requirements.txt", requirements)
                                       create_file("frontend/package.json", json.dumps(package_json, indent=2))
                                       create_file("frontend/src/App.jsx", app_jsx)
                                       create_file("frontend/src/App.css", app_css)
                                       create_file("frontend/src/index.js", index_js)
                                       create_file("frontend/public/index.html", index_html)
                                       create_file(".env", env_file)

                                       print("\n" + "=" * 50)
                                       print("✓ ALL FILES CREATED!")
                                       print("=" * 50)
                                       print("\nNext: git add . && git commit -m 'Setup files' && git push")
                                       
